### ISSUE TITLE
Consulting for dataset Tartanair

### ISSUE THREAD

**Issue by DavidYan2001** [castacks/DytanVO#15]
Dear author, 

I see that in the paper you mentioned that using Tartanair with only static scenes, I am not sure about it. Could you please share the dataset content or structure with us? Sincerely thank you!

**Comment by Geniussh** [comment]
[TartanAir](https://github.com/castacks/tartanair_tools) is the dataset we used to train our model. You refer to its page to learn about what it has and what it is. TartanAir (the version available at the time when this work was made) only contains static sequences without dynamic objects, which is why we introduced the use of cow masks in our training pipeline to model the effects that dynamic objects will bring to optical flow maps. During testing, it's recommended to use dynamic datasets such as DynaKITTI and Shibuya, though one can still use static sequences.

**Comment by Geniussh** [comment]
Closed due to lack of response
