### ISSUE TITLE
no image depth or 3d point cloud output

### ISSUE THREAD

**Issue by stihuangyuan** [castacks/DytanVO#8]
thank for your good work. there is noly poses per frame ouput in vo_trajectory_from_folder file, but no pointcloud or depth avaliable，how could i get?

**Comment by Geniussh** [comment]
Hi, thanks for your interest. Since this is VO, camera motion is expected to be the only output per the definition of VO. You can catch the depth as below, which is the intermediate output in the segmentation network. 

https://github.com/castacks/DytanVO/blob/76ea83d6fea780bfc59f1a58416e5017d0762752/Network/rigidmask/VCNplus.py#L616

You can then postprocess the image inputs and the corresponding depth maps to generate point cloud.
